name: CI - Quality, Tests, and Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Run quality checks
      - name: Run code quality checks
        run: make quality

      # 5) Run tests
      - name: Run tests
        run: make test

       # 6) Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 7) Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mohamed_khalil_4ds1_mlops:latest .

      # 8) Push Docker image
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mohamed_khalil_4ds1_mlops:latest
